development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: contact_database_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: contact_database_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres